# DockerBuild Image & Deployment of resource into local kubeadm cluster
on:  
  workflow_dispatch:

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPO : ajay996/vote

permissions:
   id-token: write
   contents: read
   actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker registry by docker
      run: |
        docker login  "${{ env.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKERHUB_USERNAME }}" -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t "${{ env.DOCKER_REPO }}":latest .
        docker tag "${{ env.DOCKER_REPO }}":latest "${{ env.DOCKER_REPO }}":${{ github.sha }}
        docker push  "${{ env.DOCKER_REPO }}":${{ github.sha }}

    - name: Install Kubectl tool
      uses: azure/setup-kubectl@v2.0

    - name: Connect Kubeadm Cluster
      uses: Azure/k8s-set-context@v2
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: check the no
      run: |
        kubectl get nodes   
        kubectl get pods